name: 🐛 Bug Report
description: Report a bug or issue with the Foundation Building Frontend
title: "[BUG]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.
  
  - type: input
    id: component
    attributes:
      label: Component/Feature Affected
      description: Which component or feature is affected?
      placeholder: "e.g., Authentication, Dashboard, API Integration"
    validations:
      required: true
  
  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: What is currently happening?
      placeholder: "Describe the current behavior that you consider problematic"
    validations:
      required: true
  
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: "Describe what you expected to happen"
    validations:
      required: true
  
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: List the exact steps to reproduce the issue
      placeholder: |
        1. Go to...
        2. Click on...
        3. Scroll down to...
        4. See error
    validations:
      required: true
  
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other (specify in additional context)
    validations:
      required: true
  
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this issue?
      options:
        - Critical (App unusable)
        - High (Major feature broken)
        - Medium (Minor feature issue)
        - Low (Cosmetic issue)
    validations:
      required: true
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: "Screenshots, logs, related issues, etc."
  
  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all necessary information to reproduce the issue
          required: true
        - label: I have tested this on the latest version
          required: true