name: ✨ Feature Request
description: Suggest a new feature or enhancement for the Foundation Building Frontend
title: "[FEATURE]: "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide detailed information about your request.
  
  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Component
        - UI/UX Enhancement
        - Performance Improvement
        - Security Enhancement
        - Integration
        - Developer Experience
        - Documentation
        - Other
    validations:
      required: true
  
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "Describe the pain point or limitation you're experiencing"
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: "What would you like to see implemented?"
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions?
      placeholder: "Describe any alternative approaches you've considered"
  
  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature?
      options:
        - Critical (Blocking current work)
        - High (Important for next release)
        - Medium (Nice to have soon)
        - Low (Future consideration)
    validations:
      required: true
  
  - type: textarea
    id: user-stories
    attributes:
      label: User Stories
      description: Provide user stories or use cases
      placeholder: |
        As a [user type], I want [functionality] so that [benefit].
        
        Example:
        As a developer, I want automated testing so that I can deploy with confidence.
  
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What criteria must be met for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
  
  - type: textarea
    id: technical-considerations
    attributes:
      label: Technical Considerations
      description: Any technical constraints or considerations?
      placeholder: "Dependencies, performance impacts, compatibility requirements, etc."
  
  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have clearly described the problem and proposed solution
          required: true
        - label: I have considered the impact on existing functionality
          required: true